<?php define_header_part(1, 'Terms and Conditions'); ?> 
<?/***********************************************************************    
* begin output buffer so we can grab the focus content
***********************************************************************/?>
<?php start_focus_content(); ?>

<div id="about_panel" class="page shdw_bot"><div class="padding">                            
<table cellspacing="0" cellpadding="0" border="0"><tr><td width="50%" valign="top" class="first">
<h3>User Agreement</h3>

<p>THIS IS A LEGAL AGREEMENT BETWEEN SAWCE MEDIA INC. (SAWCE) AND YOU AND SETS FORTH THE TERMS AND CONDITIONS THAT GOVERN THE USE OF THE SAWCE MEDIA WEBSITE (THE SITE) BY YOU. THIS AGREEMENT, TOGETHER WITH ANY AND ALL UPDATES, ADDITIONAL TERMS, AND ALL OF SAWCE'S RULES AND POLICIES, (HEREINAFTER SOMETIMES REFERRED TO COLLECTIVELY AS THE AGREEMENT) CONSTITUTE THE AGREEMENT BETWEEN SAWCE AND YOU. TO AGREE TO THESE TERMS, CLICK &quot;AGREE.&quot; IF YOU DO NOT AGREE TO THESE TERMS, DO NOT CLICK &quot;AGREE,&quot; AND DO NOT USE THE SERVICE. YOU MUST ACCEPT AND ABIDE BY THESE TERMS AND CONDITIONS AS PRESENTED TO YOU. CHANGES, ADDITIONS AND/OR DELETIONS ARE NOT ACCEPTABLE, AND SAWCE MAY REFUSE ACCESS BY YOU TO THE SITE FOR NONCOMPLIANCE WITH ANY PART OF THIS AGREEMENT.</p>
<p>1. SAWCE enables musicians to distribute and release their music online for fans to discover, buy and help market through an online distributed marketplace. The SITE is the provider of the mechanism (the SERVICE) that permits you to purchase downloads of digital content, such as sound recordings, (the MUSIC), under certain terms and conditions as set forth in this Agreement.</p>
<p>2. Age and Responsibility.</p>
<p>2.1. You represent and warrant that you are of sufficient legal age to use this  SERVICE and to create binding legal obligations for any liability you may incur  as a result of the use of this SITE. You agree to be financially responsible for all of your use of this SITE (as well as for us of your account or log-in information by others, including without limitation minors living with you ). You agree to supervise all usage by minors of this SITE under your name or account.</p>
<p>2.2. SAWCE is a general audience site that does not knowingly collect data or accept registration from minors. Furthermore, our SITE is primarily targeted to those who provide a valid credit card number.</p>
<p>3. You understand and agree that, by using the SERVICE, you may encounter MUSIC or other content that may be deemed offensive, indecent or objectionable, which content may or may not be identified as having explicit language. Nevertheless, you agree to use the SERVICE at your sole risk and you agree that SAWCE shall have and has no liability to you for content, including without limitation MUSIC, that may be found to be offensive, indecent or objectionable and/or that may or may not be identified as having explicit language. Content types (including genres, sub-genres and the like) and descriptions are provided for convenience, and you acknowledge and agree that SAWCE does not guarantee their accuracy.</p>
<p>4. System Requirements and Purchase of MUSIC.</p>
<p>4.1. Use of the SERVICE, like any Internet service, requires Internet access (fees may apply), and certain software (fees may apply), and may require obtaining updates or upgrades from time to time. Because use of the SERVICE involves hardware, software, and Internet access, your ability to use the SERVICE may be affected by the performance of these factors. High speed Internet access is strongly recommended. You acknowledge and agree that such system requirements, which may be changed from time to time, are your responsibility. The SERVICE is not part of any other music or offering, and no purchase or obtaining of any other music shall be construed to represent or guarantee you access to the SERVICE.</p>
<p>4.2. You acknowledge that use of the SITE may require the use of other hardware and software products (e.g., the ability to make copies of the MUSIC on physical media and render performance of the MUSIC on authorized digital player devices), and that such hardware and software is your responsibility. Once the MUSIC is purchased and you receive the MUSIC, it is your responsibility not to lose, destroy, or damage the MUSIC, and SAWCE shall be without liability to you in the event of any loss, destruction, or damage.</p>
<p>5. Your use of the SERVICE and purchases made through it are subject to SAWCE'S policies and any other terms and conditions required for use of the SERVICE, all of which are hereby made a part of this Agreement. If you have not already read these, you should do so now.</p>
<p>6. Except as otherwise expressly provided for in this Agreement, the SERVICE is subject to SAWCE'S Privacy Policy at http://www.sawce.net/about/privacy , which is expressly made a part of this Agreement. If you have not already read SAWCE'S Privacy Policy, you should do so now</p>
<p>7. Your Personal Information and Security.</p>
<p>7.1. You agree to provide true, accurate, current and complete information about yourself. You agree to update your Registration Information in order to keep such information current. During the registration process to use the SERVICE, you will create a password and a user name. Once you have completed the registration process, SAWCE will set up an account for you. You are solely and entirely responsible for maintaining the confidentiality of your password and user name. Furthermore, you are solely and entirely responsible for any and all activities that occur under your account. SAWCE may terminate your rights to any or all of the SERVICE if any Registration Information you provide is false, inaccurate or incomplete. You agree that SAWCE may store and use the Registration Information you provide (including credit card and PayPal account information) for use in maintaining your account and for billing fees to your credit card or PayPal account. You should not reveal your account information to anyone else or use anyone else's account. You are entirely responsible for all activities that occur on or through your account, and you agree to immediately notify SAWCE, in writing, of any unauthorized use of your account or any other breach of security. SAWCE shall not be responsible for any losses arising out of the unauthorized use of your account.</p>
<p>7.2. You shall not access or attempt to access any account that you are not authorized to access. You agree not to attempt to modify and/or to modify the SITE in any manner or form, or obtain unauthorized access to the SERVICE. Violations of system or network security may result in civil or criminal liability.</p>
<p>7.3. By agreeing to this Agreement, you expressly agree that SAWCE may use your personal information, including without limitation, to:</p>
<p>7.3.1. Deliver to you and bill you for SAWCE'S MUSIC and SERVICE, and to communicate with you, including concerning your account and customer service issues. This may include verifying authorization of credit card usage before any purchase;</p>
<p>7.3.2. Improve our SERVICE by providing personalized content recommendations and/or personalized help and instructions;</p>
<p>7.3.3. Determine if you meet the minimum system requirements to use the SITE;</p>
<p>7.3.4. Track content accesses, downloads and burns of MUSIC for the purpose of paying royalties and license fees to third party providers;</p>
<p>7.3.5. Ask you to participate in surveys about music, services, news and events;</p>
<p>7.3.6. Provide you with content, services, instructions, and a more personalized experience based on personal information, such as your zip/postal code and any content or other preferences you provide; and</p>
<p>7.3.7. Provide you with news, free newsletters, updates, targeted advertising, promotions and other related offers.</p>
<p>7.4. SAWCE does not knowingly use your personal information for purposes incompatible with those listed above. However, by agreeing to this Agreement, you acknowledge and agree that SAWCE may sell, rent, or share your non-personally-identifiable information to a third party. The third party's use of such information is governed by the privacy policy of the third party and SAWCE'S use is governed by SAWCE'S privacy policy. By your use of the SERVICE, you expressly agree that SAWCE is not liable to you, or responsible for, the alleged improper or misuse by any such third party of this non-personally-identifiable information. SAWCE also may disclose relevant information about SAWCE'S customers to its contractors (e.g., a customer service contractor or a credit card clearing service) in order for the contractors to provide specific services for SAWCE and for SAWCE to better serve its customers. SAWCE'S contractors are bound by strict contractual requirements to keep all personal information they process strictly confidential and to use such information solely on behalf of SAWCE. Also, SAWCE may disclose your personal information if required to do so by law or in the good faith belief that such action is necessary to:</p>
<p>7.4.1. confirm to the edicts of the law;</p>
<p>7.4.2. comply with the order of a competent judicial authority in any jurisdiction;</p>
<p>7.4.3. comply with legal process served on SAWCE;</p>
<p>7.4.4. protect and defend the rights or property of SAWCE; or</p>
<p>7.4.5. act in urgent circumstances to protect the personal safety of users of SAWCE, of the SITE or of the MUSIC or the public at large.</p>
<p>8. Usage Rules.</p>
<p>8.1. Your use of the SITE and the MUSIC is conditioned upon your prior acceptance of the terms of this Agreement.</p>
<p>8.2. You shall be authorized to use the MUSIC only for personal, noncommercial use.</p>
<p>8.3. You shall be entitled to export, burn (if applicable) or copy the MUSIC solely for personal, noncommercial use. Any burning (if applicable) or exporting capabilities are solely an accommodation to you and shall not constitute a grant or waiver (or other limitation or implication) of any rights of the copyright owners in any audio or video content, sound recording, underlying musical composition, or artwork embodied in any music.</p>
<p>8.4. You agree that you will not attempt to, or encourage or assist any other person to, circumvent or modify any security technology or software that is part of the SERVICE.</p>
<p>8.5. The delivery of the MUSIC does not transfer to you any commercial or promotional use rights in the MUSIC.</p>
<p>8.6. You agree that your purchase of the MUSIC constitutes your acceptance of and agreement to use such MUSIC solely in accordance with the Rules of SAWCE, and that any other use of the MUSIC may constitute a copyright infringement. The Rules of SAWCE shall govern your rights with respect to the MUSIC, in addition to any other terms or rules that may have been established between you and another party. SAWCE reserves the right to modify the Rules of SAWCE at any time.</p>
<p>8.7. The SERVICE may offer interactive features that allow you to, among other things, submit or post information, materials or links to third party content on areas of the SERVICE accessible and viewable by other users of the SERVICE and the public. You represent and agree that any use by you of such features, including any information, materials or links submitted or posted by you, shall be your sole responsibility, shall not infringe or violate the rights of any other party or violate any laws, contribute to or encourage infringing or otherwise unlawful conduct, or otherwise be obscene, objectionable or in poor taste, and that you have obtained all necessary rights, licenses or clearances. You further agree to provide accurate and complete information in connection with your submission or posting of any information or materials on the SERVICE. Moreover, you hereby grant SAWCE a worldwide, royalty-free, non-exclusive license to use such materials as part of the SERVICE, and in relation to MUSIC, without any compensation or obligation to you.</p>
<p>8.8. SAWCE reserves the right not to post or publish any materials, and to delete, remove or edit any material, at any time in its sole discretion without notice or liability.</p>
<p>8.9. SAWCE has the right, but not the obligation, to monitor any information and materials submitted or posted by you or otherwise available on the SERVICE, to investigate any reported or apparent violation of this Agreement, and to take any action that SAWCE in its sole discretion deems appropriate, including, without limitation, under Section 12 below or under our Copyright Policy.</p>
<p>9. Agreement to Pay.</p>
<p>9.1. Payment for the MUSIC. You agree to pay for all MUSIC you purchase through the SERVICE, and that SAWCE may charge your account with SAWCE, your credit card account or your PayPal account for any MUSIC purchased, as may be accrued by or in connection with your Account. YOU ARE RESPONSIBLE FOR THE TIMELY PAYMENT OF ALL FEES AND FOR PROVIDING SAWCE WITH A VALID CREDIT CARD OR PAYPAL ACCOUNT DETAILS FOR PAYMENT OF ALL FEES OR MAINTAINING AN APPROPRIATE BALANCE, AS DETERMINED BY SAWCE IN ITS SOLE DISCRETION, IN YOUR SAWCE ACCOUNT. All fees will be billed to your SAWCE account, to the credit card, or the PayPal account that you designate during the registration process. If you want to designate a different credit card or if there is a change in your credit card or PayPal account status, you must change your credit card or PayPal account information online at the Account Information section of the SERVICE. (There may be a temporary disruption of your access to the SERVICE until SAWCE can verify the validity of the new credit card or PayPal account information.)</p>
<p>9.2. Right to Change Prices and Availability of the MUSIC. Prices and availability of any MUSIC are subject to change at any time, in SAWCE'S sole discretion. The minimum amount required to be maintained in your SAWCE account is subject to change at any time, in SAWCE'S sole discretion.</p>
<p>9.3. Electronic Signatures and Contracts. Your use of the SERVICE includes the ability to enter into agreements and/or to make purchases electronically. YOU ACKNOWLEDGE THAT YOUR ELECTRONIC SUBMISSIONS CONSTITUTE YOUR AGREEMENT AND INTENT TO BE BOUND BY AND TO PAY FOR SUCH AGREEMENTS AND PURCHASES. YOUR AGREEMENT AND INTENT TO BE BOUND BY ELECTRONIC SUBMISSIONS APPLIES TO ALL RECORDS RELATING TO ALL TRANSACTIONS YOU ENTER INTO ON THIS SITE, INCLUDING NOTICES OF CANCELLATION, POLICIES, CONTRACTS, AND APPLICATIONS.</p>
<p>9.4. Any unused credit stored in your SAWCE account will expire, without refund, fifteen (15) months after it was purchased</p>
<p>10. On occasion, technical problems may delay or prevent delivery of the MUSIC. Your exclusive and sole remedy with respect to MUSIC that is not delivered within a reasonable period will be either replacement of such MUSIC, or refund of the purchase price paid for such MUSIC, as determined by SAWCE in its sole discretion.</p>
<p>11. Intellectual Property.</p>
<p>11.1. You agree that the SERVICE, including but not limited to graphics, audio clips, and editorial content, contains proprietary information and material that is owned by SAWCE and/or its licensors, and is protected by applicable intellectual property and other laws, including but not limited to copyright, and that you will not use such proprietary information or materials in any way whatsoever except for use of the SERVICE in compliance with the terms of this Agreement. No portion of the SERVICE may be reproduced in any form or by any means. You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the SERVICE, in any manner, and you shall not exploit the SERVICE in any unauthorized way whatsoever, including but not limited to, by trespass or burdening network capacity.</p>
<p>11.2. Notwithstanding any other provision of this Agreement, SAWCE and its licensors reserve the right to change, suspend, remove, or disable access to any MUSIC, content, or other materials comprising a part of the SERVICE at any time without notice. In no event will SAWCE be liable for the removal of or disabling of access to any such MUSIC, content or materials under this Agreement. SAWCE may also impose limits on the use of or access to certain features or portions of the SERVICE, in any case and without notice or liability.</p>
<p>11.3. All copyrights in and to the SERVICE, including but not limited to, the SITE (including the compilation of content, postings, links to other Internet resources, and descriptions of those resources), and software, are owned by SAWCE and/or its licensors. THE USE OF THE SOFTWARE OR ANY PART OF THE SERVICE, EXCEPT FOR USE OF THE SERVICE AS PERMITTED IN THESE TERMS OF SERVICE, IS STRICTLY PROHIBITED AND INFRINGES ON THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS AND MAY SUBJECT YOU TO CIVIL AND CRIMINAL PENALTIES, INCLUDING POSSIBLE MONETARY DAMAGES, FOR COPYRIGHT INFRINGEMENT.</p>
<p>11.4. SAWCE, the SAWCE logo, the SITE, and other SAWCE trademarks, service marks, graphics, and logos used in connection with the SERVICE are trademarks or registered trademarks of SAWCE Media Inc. in Canada and/or other countries. Other trademarks, service marks, graphics, and logos used in connection with the SERVICE may be the trademarks of their respective owners. You are granted no right or license with respect to any of the aforesaid trademarks and any use of such trademarks.</p>
<p>12. Termination.</p>
<p>12.1. If you fail, or SAWCE suspects that you have failed, to comply with any of the provisions of this Agreement, including but not limited to failure to make payment of fees due, failure to provide SAWCE with a valid credit card or with accurate and complete Registration Information, failure to safeguard your Account information, violation of the Usage Rules or any license to the software, or infringement or other violation of third parties' rights, SAWCE, at its sole discretion, without notice to you may: (i) terminate this Agreement and/or your Account, and you will remain liable for all amounts due under your Account up to and including the date of termination; and/or (ii) terminate the license to the software; and/or (iii) preclude access to the SERVICE (or any part thereof).</p>
<p>12.2. Termination of the SERVICE. SAWCE reserves the right to modify, suspend, or discontinue the SERVICE (or any part or content thereof) at any time with or without notice to you, and SAWCE will not be liable to you or to any third party should it exercise such rights.</p>
<p>12.3. At SAWCE'S discretion and in appropriate circumstances, SAWCE may revoke the accounts of users who infringe upon the copyright, or other intellectual property rights, of others. If you are an artist or other copyright holder who believes that SAWCE'S MUSIC SERVICE or the SITE is hosting or linking directly to infringing copies of your work, please let us know immediately via email to <a href="mailto:legal@sawce.net.(is">legal@sawce.net.(is</a> this a valid email address?)</p>
<p>13. The SERVICE is controlled and operated by SAWCE from its offices in Canada. You agree to comply with all local, provincial and federal, laws, statutes, ordinances, and regulations that apply to your use of the SERVICE.</p>
<p>14. SAWCE reserves the right to takes steps SAWCE believes are reasonably necessary or appropriate to enforce and/or verify compliance with any part of this Agreement (including but not limited to SAWCE'S right to cooperate with any legal process relating to your use of the SERVICE and/or MUSIC, and/or a third party claim that your use of the SERVICE and/or MUSIC is unlawful and/or infringes such third party's rights). You agree that SAWCE has the right, without liability to you, to disclose any Registration Information and/or Account information to law enforcement authorities, government officials, and/or a third party, as SAWCE believes is reasonably necessary or appropriate to enforce and/or verify compliance with any part of this Agreement (including but not limited to SAWCE'S right to cooperate with any legal process relating to your use of the SERVICE and/or MUSIC, and/or a third party claim that your use of the SERVICE and/or MUSIC is unlawful and/or infringes such third party's rights).</p>
<p>15. Certain content, MUSIC, and services available via the SERVICE may include materials from third parties. In addition, SAWCE may provide links to certain third party Web sites. You acknowledge and agree that SAWCE is not responsible for examining or evaluating the content or accuracy of any such third-party material or Web sites. SAWCE does not warrant or endorse and does not assume and will not have any liability or responsibility for any third-party materials or Web sites, or for any other materials, MUSIC, or services of third parties. Links to other Web sites are provided solely as a convenience to you. You agree that you will not use any third-party materials in a manner that would infringe or violate the rights of any other party, and that SAWCE is not in any way responsible for any such use by you.</p>
<p>16. Disclaimer of Warranties; Liability Limitations.</p>
<p>16.1. SAWCE DOES NOT GUARANTEE, REPRESENT, OR WARRANT THAT YOUR USE OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, AND YOU AGREE THAT FROM TIME TO TIME SAWCE MAY REMOVE THE SERVICE FOR INDEFINITE PERIODS OF TIME, OR CANCEL THE SERVICE AT ANY TIME, WITHOUT NOTICE TO YOU.</p>
<p>16.2. YOU EXPRESSLY AGREE THAT YOUR USE OF, OR INABILITY TO USE, THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE AND ALL MUISC AND SERVICES DELIVERED TO YOU THROUGH THE SERVICE ARE (EXCEPT AS EXPRESSLY STATED BY SAWCE) PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; FOR YOUR USE, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, THE ABOVE EXCLUSION OF IMPLIED WARRANTIES MAY NOT APPLY TO YOU.</p>
<p>16.3. IN NO CASE SHALL SAWCE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF ANY OF THE SERVICES OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR USE OF THE SERVICES, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR OMISSIONS IN ANY CONTENT, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT (OR MUSIC) POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICE, EVEN IF ADVISED OF THEIR POSSIBILITY. BECAUSE SOME PROVINCES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH PROVINCES OR JURISDICTIONS, SAWCE'S LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
<p>16.4. SAWCE SHALL USE REASONABLE EFFORTS TO PROTECT INFORMATION SUBMITTED BY YOU IN CONNECTION WITH THE SERVICES, BUT YOU ACKNOWLEDGE AND AGREE THAT YOUR SUBMISSION OF SUCH INFORMATION IS AT YOUR SOLE RISK, AND SAWCE HEREBY DISCLAIMS ANY AND ALL LIABILITY TO YOU FOR ANY LOSS OR LIABILITY RELATING TO SUCH INFORMATION IN ANY WAY.</p>
<p>16.5. SAWCE DOES NOT REPRESENT OR GUARANTEE THAT THE SERVICE WILL BE FREE FROM LOSS, CORRUPTION, ATTACK, VIRUSES, INTERFERENCE, HACKING, OR OTHER SECURITY INTRUSION, AND SAWCE DISCLAIMS ANY LIABILITY RELATING THERETO. YOU SHALL BE RESPONSIBLE FOR BACKING UP YOUR OWN SYSTEM.</p>
<p>17. BY USING THE SERVICE, YOU AGREE TO INDEMNIFY AND HOLD SAWCE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, AND LICENSORS HARMLESS WITH RESPECT TO ANY CLAIMS ARISING OUT OF YOUR BREACH OF THIS AGREEMENT, YOUR USE OF THE SERVICE, OR ANY ACTION TAKEN BY SAWCE AS PART OF ITS INVESTIGATION OF A SUSPECTED VIOLATION OF THIS AGREEMENT OR AS A RESULT OF ITS FINDING OR DECISION THAT A VIOLATION OF THIS AGREEMENT HAS OCCURRED. THIS MEANS THAT YOU CANNOT SUE OR RECOVER ANY DAMAGES FROM SAWCE, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, AND LICENSORS AS A RESULT OF ITS DECISION TO REMOVE OR REFUSE TO PROCESS ANY INFORMATION OR CONTENT, TO WARN YOU, TO SUSPEND OR TERMINATE YOUR ACCESS TO THE SERVICE, OR TO TAKE ANY OTHER ACTION DURING THE INVESTIGATION OF A SUSPECTED VIOLATION OR AS A RESULT OF SAWCE'S CONCLUSION THAT A VIOLATION OF THIS AGREEMENT HAS OCCURRED. THIS WAIVER AND INDEMNITY PROVISION APPLIES TO ALL VIOLATIONS DESCRIBED IN OR CONTEMPLATED BY THIS AGREEMENT.</p>
<p>18. SAWCE reserves the right, at any time and from time to time, to update, revise, supplement, and otherwise modify this Agreement and to impose new or additional rules, policies, terms, or conditions on your use of the SERVICE. Such updates, revisions, supplements, modifications, and additional rules, policies, terms, and conditions (collectively referred to in this Agreement as &quot;Additional Terms&quot;) will be effective immediately and incorporated into this Agreement. Your continued use of the SITE will be deemed to constitute your acceptance of any and all such Additional Terms. All Additional Terms are hereby incorporated into this Agreement by this reference.</p>
<p>19. SAWCE may send you notice with respect to the SERVICE by sending an email message to the email address listed in your SAWCE Account contact information, by sending a letter via postal mail to the contact address listed in your SAWCE Account contact information, or by a posting on the SITE. Notices shall become effective immediately.</p>
<p>20. The laws of the Province of British Columbia, excluding its conflicts of law rules, govern these Terms and your use of the SERVICE. Your use of the SERVICE may also be subject to other local, provincial, federal, or international laws. You expressly agree that exclusive jurisdiction for any claim or dispute with SAWCE or relating in any way to your use of the SERVICE resides in the courts of the Province of British Columbia.</p>
<p>21. These Terms of SERVICE constitute the entire agreement between SAWCE and you and govern your use of the SERVICE, superseding any prior agreements between SAWCE and you. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third-party content, or third-party software. If any part of these Terms of SERVICE is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect. SAWCE'S failure to enforce any right or provisions in these Terms of SERVICE will not constitute a waiver of such provision, or any other provision of these Terms of SERVICE. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the other provisions will remain in full force and effect. SAWCE will not be responsible for failures to fulfill any obligations due to causes beyond its control.</p>
 
</td><td width="50%" valign="top">
<h3>Content Provider Agreement</h3>

<p>This Content Provider Agreement (hereinafter the &quot;Agreement&quot;) is made and entered by and between SawceMedia Inc. (&quot;SAWCE&quot;), the owner and operator of the website known as &quot;Sawce&quot; with an Internet URL of www.sawce.net, and the Content Provider with name and email address as set forth in the &quot;contact information&quot; provided by the user (hereinafter the &quot;Provider&quot;). SAWCE and the Provider are sometimes hereinafter referred to individually as a &quot;Party&quot; or collectively as the &quot;Parties.&quot;</p>
<p>1.00. The Agreement is effective as of the date of execution by Provider (the &quot;Effective Date&quot;) and shall remain in effect during the Term (as detailed below in section 3.04. The Agreement sets forth the terms and conditions hereinafter agreed to by and between the Parties, including without limitation, the Provider's uploading of content (whether user generated or otherwise developed) onto the Site (as defined in 2.00) and onto the SAWCE servers, and in connection with SAWCE'S sale or proposed sale on and through the Site, of certain musical content and the performances embodied thereon, as more fully set forth below.</p>
<p>1.01. Provider and SAWCE are independent parties and have no partnership affiliation between or among them. It is expressly acknowledged by the parties that no joint venture and/or employer-employee status is created by virtue of the parties entering into this Agreement.</p>
<p>2.00. Provider agrees to submit to SAWCE the Provider's musical recording(s) (or materials which the Provider has exclusive license to), with individual titles to be selected at the sole discretion of Provider, along with all applicable cover art, meta-data, and any other materials needed by SAWCE to prepare Provider's musical recording(s) for sale and distribution (collectively hereinafter referred to as the &quot;Content&quot;) by uploading the Content directly onto the Site in accordance with the instructions for uploading provided to the Provided by SAWCE and as appears on the Site. The &quot;Site&quot; shall include the website located at www.sawce.net as well as all uses of the &quot;widget&quot; as described below in section 2.07(d) of the Agreement.</p>
<p>2.01. Provider hereby agrees to provide the Content, as soon as possible and without further demand, to SAWCE for sale, display, download, and/or use on the Site. The Content shall be displayed and made available for sale, download and/use on the Site at SAWCE'S sole discretion. Provider hereby expressly acknowledges and agrees that any additional Content that is submitted by Provider (unless and until this Agreement is revoked by either Party in writing) to the Site shall be governed by the terms and conditions of this Agreement.</p>
<p>2.02. Provider hereby represents and warrants that Provider is the sole and exclusive holder of any and all rights in and to the Content, and/or an authorized representative or agent of the holder(s) (with written authority to act on behalf of the exclusive owner) of any and all such rights for the purposes of use/license of the Content (and the scope of such use and license) as set forth in this Agreement. Provider represents and warrants that Provider is free to enter into and abide by the terms of this Agreement and that Provider owns and/or controls all necessary rights required to legally provide/license/offer the Content submitted to SAWCE for sale, display, download, and/or use in accordance with the terms of this Agreement.</p>
<p>2.03. Provider hereby expressly agrees to and will indemnify and hold SAWCE (and its owners, officers, directors, employees, agents and representatives or affiliates) harmless, including without limitation with respect to its legal fees and costs, against any and all losses, damages, claims, actions and proceedings brought against SAWCE arising from the sale, display, download, and/or use of the Content, or any portion thereof, in accordance with the terms of this Agreement.</p>
<p>2.04. Provider to be responsible for samples and royalty payment. Provider hereby expressly warrants and represents that Provider is and will be solely responsible for all applicable royalties due to the holder(s) of any rights (or sub-rights) in and to any Content by reason of any sale, display, download, sampling, infringement claims and/or use of any Content in any way and in any media now known or hereinafter discovered, including, but not limited to, master recording royalties, performance royalties and publisher royalties. Provider further agrees to and will indemnify and hold SAWCE (and its owners, officers, directors, employees, agents, representatives and/or affiliates) harmless against any and all losses, damages, costs, claims, actions and proceedings, including without limitation attorneys' fees and costs, or resulting from the services of the artists, musicians, song writers, and any other rights holder(s) whose work (or a portion of whose work) Provider submits to SAWCE for sale, display, download, and/or use.</p>
<p>2.05. Provider further warrants and represents that there are no liens, encumbrances and/or obligations upon and/or in connection with any master recording underlying any performance submitted as Content (each a &quot;Master&quot; and collectively &quot;Masters&quot;), and/or in connection with any submitted performances that are not specifically set forth herein. In addition to the representation and warranty that the Provider has the unfettered authority to provide said Content to SAWCE, Provider hereby represents that the Content is unencumbered by any liens or encumbrances to Provider's title or right to license or provide same to SAWCE. </p>
<p>2.06. Provider hereby agrees and warrants that Provider is required to obtain all necessary mechanical licenses from the copyright owner(s) of the compositions embodied on all Masters, to pay mechanical license fees, and synch license fees, which are and/or may become properly due by reason of the sale of Content derived from any and all Masters. In the event that Provider is the copyright owner of any composition and/or compositions embodied on said Master, Provider warrants and represents that Provider has issued to itself the necessary documents required by the copyright office. </p>
<p>2.07. During the Term (as defined herein) or any extension thereof, Provider hereby grants to SAWCE, for the term of this Agreement, the following rights:</p>
<p>(a) the non-exclusive right to electronically distribute in the Universe via the Site, without any limitation not specifically set forth herein or hereinafter, in and to the Masters and all electronic copies thereof and in and to the performances embodied thereon including but not limited to the right to make, cause or otherwise effect Digital Audio Transmissions and Digital Phonorecord Deliveries of the Licensed Masters (&quot;Electronic Distribution&quot;) without any digital rights management restrictions. The term &quot;Digital Audio Transmission&quot; shall mean a transmission that embodies a sound recording including the performance thereof. The term &quot;Digital Phonorecord Delivery&quot; shall mean each individual delivery of a phonorecord by digital transmission of a sound recording which results in a specifically identifiable reproduction by or for any transmission recipient of a phonorecord of that sound recording. The term &quot;Licensed Masters&quot; shall mean all sound recordings owned or controlled by the Provider at any time during the Term.</p>
<p>(b) the non-exclusive right during the Term, throughout the Universe via the Site, to use, reproduce, display, perform, distribute, transmit, publicly and privately, by any and all means and in any and all media now known or hereafter devised without any digital rights management restrictions: (a) the names, approved likenesses and biographical information (including professional, group, and other assumed or fictitious names) of any and all persons performing on or rendering services in connection with the creation of Licensed Masters, as well as of the Label (collectively, &quot;Name and Likeness&quot;); (b) any artwork, drawings, photographs, liner notes and/or other graphical materials furnished or identified by Label for SAWCE'S use hereunder (collectively, &quot;Artwork&quot;); and (c) any trademarks, service marks or trade names embodied in the foregoing (collectively &quot;Marks&quot;). No so-called &quot;merchandising rights&quot; in and to the Artwork, Name and Likeness or Marks are granted by Provider hereunder.</p>
<p>(c) the non-exclusive right and license during the Term and throughout the Universe via the Site to use, reproduce, distribute, display, deliver and transmit, publicly and privately, by any means now known or hereafter devised, the lyrics of the Controlled Compositions (as defined herein) embodied in the Licensed Masters, solely for the purpose of promoting the Licensed Masters or facilitating the exercise of the rights of Electronic Distribution of the Licensed Masters. The term &quot;Controlled Compositions&quot; shall mean any and all musical works embodied in the Licensed Masters which are owned or controlled, directly or indirectly, by Provider, collectively or individually. </p>
<p>(d) the rights granted to SAWCE herein shall specifically include the right to use the SAWCE &quot;widget&quot; or media player on the Site, through the Site, or in any other way related to the Site. For example, and without limitation, the right to use an embedded player on www.myspace.com to play, sell and download the Provider Content, which is linked to the Site. In addition and for the sake of clarity, the aforementioned grant of rights to SAWCE shall specifically include the right to use and/or sell the Provider Content through any of SAWCE'S partner's, affiliates or licensees' websites understanding that the Provider Content shall remain on the SAWCE Network or database (the &quot;Back End&quot;) despite the appearance of a non-SAWCE branded player (the &quot;Front End&quot;). Provider acknowledges and agrees that the within grant of rights shall include a grant to SAWCE authorizing SAWCE to &quot;whitelabel&quot; the Provider Content on the Front End while maintaining the Provider Content on the Back End.</p>
<p>(e) In addition to the right granted in paragraph 2.07(a) through 2.07(d), Provider hereby assigns, transfers and grants to SAWCE for the Term of this Agreement, the non-exclusive, worldwide right and license to sell, display, download, distribute and/or use, in accordance with the terms of this Agreement, including, without any limitation, not specifically set forth hereinafter, the following:</p>
<p>2.07.1. The right to sell the Content provided to SAWCE by Provider, and all or any parts thereof, edited and/or excerpted by any means whatsoever, for the term of this Agreement.</p>
<p>2.07.2. The right to sell, and/or refrain from selling, the Contents of any Master, for any reason.</p>
<p>2.07.3. The right to use and publish and to permit others to use and publish the names, likenesses and photographs of all persons who performed in the recording of the Master, in connection with the sale and exploitation of Content of the performance(s) produced from the Master.</p>
<p>2.07.4. Provider agrees to utilize and provide Provider's best efforts to include, as soon as possible, a link to the Site from any website related to Provider and/or owned, operated, or maintained by Provider and/or on Provider's behalf.</p>
<p>2.07.5. As used herein, the term &quot;use&quot; as it applies to the Content includes, without limitation, the right to stream musical and/or other Content at no additional cost or charge to SAWCE. The term &quot;use&quot; shall also include SAWCE'S use of Content titles and artist names in connection with a &quot;music market&quot; to be utilized by users of the Site wishing to invest and/or speculate in the popularity of any Content offered for sale on the Site, at no additional cost or charge to SAWCE. This provision, 2.07.5, refers to the SAWCE recommendation system and affiliate system.</p>
<p>2.07.6. SAWCE shall have the right, and throughout the term of this Agreement shall continue to retain the right, to remove from the Site any and all Content for any reason whatsoever, including without limitation Content that SAWCE deems, in SAWCE'S sole discretion and judgment, to be illegal, unsafe, scandalous, obscene, libelous or of a morally deviant nature, and/or otherwise inappropriate, without any claim, recourse and/or right by Provider. Content uploaded to the Site shall remain on the Site unless removed by SAWCE in accordance herewith, and/or requested to be removed by Provider, in writing. If Provider requests that the Content be removed from the Site, Provider shall state the reason for the removal request. SAWCE will, within sixty (60) calendar days of Provider's notice, remove the Content from the Site. However, it is expressly agreed that a Provider shall not be permitted to request removal of Content submitted to the Site under the terms of this Agreement for a period of sixty (60) calendar days from the date Provider uploads such Content onto the Site (hereinafter the &quot;Upload Date&quot;).</p>
<p>3.00. In full and complete consideration of the performance of all the terms and provisions to be performed by Provider, and for all the rights granted to SAWCE hereunder, SAWCE agrees to pay to Provider an amount (the &quot;Provider Payment&quot;) equal to the net sales price of any Content sold on the Site (or by virtue of any partnership with SAWCE) to any third party (&quot;Sales Revenue&quot;), minus a fixed percentage of no greater than thirty percent (30%) of such Sales Revenue (&quot;Retained Percentage&quot;) per song. In addition, an initial one-time listing fee (&quot;Listing Fee&quot;) of no greater than Five Dollars ($5.00) per unit of Content will be deducted from the Sales Revenue. For the sake of clarity, the Provider Payment is 70% of the Sales Revenue after the Listing Fee for each unit of Content sold on the Site is deducted from the Sales Revenue.</p>
<p>3.00.1. The Retained Percentage is subject to change by SAWCE, in SAWCE'S sole discretion and judgment, upon prior written notice to Provider, including notice via email, text message, etc., provided however, that no increase shall be effective during the first one hundred twenty (120) calendar days from the Upload Date. Notwithstanding the aforementioned, the Provider retains the right to opt out of the service, within fifteen (15) days of SAWCE'S notice to Provider of said increase, if an increase in the Retained Percentage is found to be disagreeable to the Provider after consultation and discussion with SAWCE.</p>
<p>3.01. No later than thirty (30) calendar days after the end of a Pay Period, which is to be no longer than three (3) calendar months, and assuming the receipt by SAWCE of Sales Revenue from downloaded Content, SAWCE shall make the Provider Payment due Provider pursuant to Paragraph 3.00 above. This provision shall be in effect so long as there is at least Ten Dollars ($10.00) in Provider Payment from the sale of Provider's Content during the preceding Pay Period. If the Provider Payment is not at least Ten Dollars ($10.00) from the sale of Content through the Site for a given Pay Period, then SAWCE shall be entitled to retain that revenue and apply it to each successive Pay Period until Provider has earned at least Ten Dollars ($10.00) of cumulative Provider Payment. Once Provider has earned at least Ten Dollars ($10.00) in cumulative Provider Payment, including any cumulative Provider Payment from prior Pay Periods, SAWCE shall pay the Provider's Payment no more than three (3) calendar months thereafter. In the event that this Agreement is terminated, SAWCE shall pay the Provider's Payment no more than three (3) calendar months thereafter upon due demand.</p>
<p>3.02. Provider acknowledges that Provider is responsible for immediately notifying SAWCE, in writing, of any address and/or notice changes where Provider is to receive payment and/or notice. Provider assumes all responsibility with respect to advising SAWCE of any change in notice address. In the event a Provider Payment does not reach Provider due to a failure to provide updated mailing address information or updated PayPal account information, Provider hereby absolves SAWCE from any liability in connection with such failure. </p>
<p>3.03. The initial term of this Agreement (&quot;Term&quot;) shall consist of a period of two (2) years commencing on the Effective Date listed above. The Term shall be automatically extended for consecutive one (1) year periods, unless terminated by either party by written notice to the other party at least sixty (60) days before the end of the then applicable term. This Agreement may be cancelled upon sixty (60) calendar days advance written notice by either Party after an initial term of sixty (60) calendar days. It is hereby acknowledged by Provider that the Provider's Content will be offered for sale through the Site (and through SAWCE'S Strategic Network Partners, if separately agreed to by the parties) until this Agreement is validly terminated by either Party hereto. If not validly terminated by either party, this Agreement will renew thereafter automatically on the same terms and conditions for additional successive annual periods without the need for further action by either party.</p>
<p>3.04. It is hereby agreed to and acknowledged by the parties that in order to better serve its customers and Providers, SAWCE shall have the right to compile and use statistics related to the sale of Provider's Content and of Provider's purchases to better understand the Provider and his/her preferences, etc. SAWCE hereby expressly reserves the right to collect information about its users, including, without limitation, information about its Provider, via cookies and recorded data from SAWCE'S servers and/or partners. </p>
<p>3.04.1. It is expressly agreed to by the parties to this Agreement that it is permissible for SAWCE to provide and/or sell any or all of the collected information to SAWCE'S business partners, in SAWCE'S sole discretion and judgment, without the necessity of notice to, approval by, and/or compensation to Provider; provided, however, except as otherwise provide on the Site, that in accordance with SAWCE'S Privacy Policy, as set forth elsewhere on this Site, SAWCE will take reasonable steps to avoid knowingly disclosing its Providers' names, addresses, telephone numbers, email addresses, banking information and/or address without first notifying Provider in advance in sufficient time to allow its Providers to object and to legally prevent SAWCE from disclosing said information. </p>
<p>3.04.2. In addition, by using this Site, Provider acknowledges and agrees that Internet transmissions are never completely private or secure. Provider acknowledges and understands that any message or information sent to SAWCE may be read or intercepted by others, even if there is a special notice that a particular transaction or transmission (for example, credit card information) is encrypted. </p>
<p>3.05. It is hereby acknowledged by the Provider that Provider shall be fully responsible for any and all taxes, interest and penalties arising from receipt by Provider of any Provider Payment from SAWCE. In addition to the general indemnification granted elsewhere by Provider to SAWCE, Provider hereby agrees to indemnify and hold SAWCE, its officers, directors, shareholders, predecessors, successors-in-interest, employees, agents, subsidiaries and affiliates, harmless from any demands, loss, liability claims or expenses (including attorneys' fees), made against SAWCE by any third party due to or arising out of or in connection with Provider's uses of the Site.</p>
<p>4.00. Provider agrees to and shall be responsible for any costs, attorneys' fees and/or damages incurred or assessed against SAWCE and its owners, officers, directors, employees, agents and representatives because of and/or arising out of any action taken in response to, and/or suggested by, Provider's Content, including, but not limited to, suggestions and/or or inducements that a listener should and/or engage in any illegal, unsafe, scandalous, obscene, libelous or morally deviant and/or otherwise inappropriate behavior.</p>
<p>4.00.1. Provider agrees to and will indemnify and hold SAWCE (and its owners, officers, directors, employees, agents and representatives) harmless, and Provider agrees to and will pay any defense costs, attorneys' fees and costs as well as any and all damages and/or payments assessed against SAWCE on account of any illegal, unsafe, scandalous, obscene, libelous or morally deviant and/or otherwise inappropriate material contained in Provider's Content.</p>
<p>4.01. SAWCE shall not be responsible for editing any Content and Provider will have no editorial control over the Content after its submission. However, SAWCE retains the right, in its sole discretion, to delete and/or decline to use any Content that in SAWCE'S opinion is illegal, unsafe, scandalous, obscene, libelous, morally deviant and/or otherwise of an inappropriate nature.</p>
<p>4.02. Provider agrees and warrants that Provider shall immediately notify SAWCE, in writing to the notice address listed herein, if any claim of infringement, obscenity, incitement, or any other legal action is brought against Provider in connection with any Content, including, without limitation, any claim pursuant to Paragraphs 2.01, 2.02, 2.03, 2.04, 2.05 and 3.04.</p>
<p>4.03. This Agreement is personal to Provider. Provider may not assign or otherwise transfer Provider's rights and duties under this Agreement without prior written notice to SAWCE and written consent of SAWCE. Any such purported assignment without notification is null and void. </p>
<p>5.00. Provider hereby agrees and acknowledges that this Agreement shall be deemed to have been made in the Province of British Columbia and shall be interpreted and governed by the laws of that province, without regard to its conflict of laws provisions. Provider agrees and submits to the personal jurisdiction and venue in the provincial and/or federal courts in the Province of British Columbia. Notwithstanding the statutory period of limitations provided for in British Columbia, it is hereby acknowledged and agreed by the Provider that any claim under or in connection with this Agreement related to allegations that SAWCE breached the Agreement shall be brought within one (1) year after the cause of action accrues, or such claim or cause of action is time-barred. In the event of any controversy or dispute between SAWCE and Provider arising out of or in connection with the use of the Site, the parties shall attempt, promptly and in good faith, to resolve any such dispute. If the parties are unable to resolve any such dispute within a reasonable time (not to exceed thirty (30) days), then either party may submit such controversy or dispute to mediation pursuant to paragraph 5.01 below.</p>
<p>5.01. If any disputes and/or differences whatsoever shall arise between the Parties in connection with the compliance, interpretation and/or enforcement of this Agreement, any and all such disputes and/or differences shall be submitted to mediation in Vancouver, British Columbia, before a mediator mutually selected by the Parties. If mediation is not successful, or within thirty (30) calendar days, whichever occurs first, either Party may request the dispute be submitted to final and binding arbitration, in Vancouver, British Columbia, before an arbitrator mutually selected by the Parties. If the Parties cannot mutually agree upon the selection of an Arbitrator within two (2) weeks, the Parties shall select an Arbitrator as provided in the Commercial Arbitration Act of British Columbia for commercial disputes. The Arbitrator chosen shall be bound by the express terms of this Agreement, except as necessary to comply with the requirements of applicable case law, and shall hear and determine all disputes as presented to him or her as expeditiously and economically as possible. To the extent consistent with applicable statutory and case law, the Prevailing Party in any action, proceeding or arbitration shall be entitled to recover not only the amount of any damages, judgment, award or settlement in favor of said Party, if any, but also such other damages, costs and expenses as may be actually incurred by said Party, including Court costs, reasonable attorneys' fees, or expert witness or consultant fees incurred in connection with such action, proceeding or arbitration. Any award of the Arbitrator shall be final and binding and may be confirmed as a final judgment in any Court of competent jurisdiction in British Columbia. The courts of the Province of British Columbia shall have the exclusive jurisdiction over both of the Parties and their property to enforce any resolution or the award of the Arbitrator. Provider hereby waives any challenge to venue, including forum non-conveniens.</p>
<p>6.00. NO PARTY SHALL BE LIABLE TO THE OTHER PARTY FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL AND/OR PUNITIVE DAMAGES RELATING TO THE PERFORMANCE OF THIS AGREEMENT, AND/OR ARISING HEREUNDER, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT. EACH PARTY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. EXCEPT AS EXPRESSLY PROVIDED FOR IN THIS AGREEMENT (INCLUDING WITHOUT LIMIATION, NO REPRESENTATION OR AFFIRMATION OF FACT, INCLUDING, BUT NOT LIMITED TO, STATEMENTS REGARDING SUITABILITY FOR USE OR PERFORMANCE OF THE PLATFORM OR THE AFFILIATE TECHNOLOGY), WHETHER MADE BY A PARTY'S REPRESENTATIVE, EMPLOYEE OR OTHERWISE, SHALL BE DEEMED TO BE A WARRANTY BY THAT PARTY FOR ANY PURPOSE, AND/OR GIVE RISE TO ANY LIABILITY OF THAT PARTY. THE TOTAL AGGREGATE LIABILITY OF SAWCE TO THE PROVIDER FOR ALL CLAIMS ARISING OUR OF OR IN CONNECTION WITH THIS AGREEMENT SHALL NOT EXCEED ALL FEES AND COMMISSIONS COLLECTED OR DUE HEREUNDER.</p>
<p>6.01. It is hereby acknowledged and agreed to by the Parties that the Internet is sometimes unreliable, slow or inactive. As such, the parties agree that SAWCE shall not be responsible for any delays and/or errors in fulfilling orders for Provider's Content caused by SAWCE'S Internet connection, equipment (including server) failure, distributors and/or delivery services and/or by Acts of God, and/or any other cause beyond the control of SAWCE. SAWCE shall not be responsible for any failure to list the submitted Content due to transmission errors and/or any other cause beyond the control of SAWCE.</p>
<p>6.02. Inadvertent/Minor Errors Not a Material Breach. It is hereby acknowledged and agreed to by the Parties that, although SAWCE uses its best efforts to accurately account, there may be minor, inadvertent accounting errors due to the number of transactions processed by SAWCE, coupled with the fractional dollar amount of many of these transactions. Provider will have the right to request, not more than once per calendar year and at Provider's expense, an audit of SAWCE'S records to verify the accuracy of SAWCE'S accounting in regard to Provider's Content (an &quot;Audit Request&quot;). Such Audit Request is subject to SAWCE'S agreement, which may be withheld in SAWCE'S sole discretion. An audit, should Provider's request be granted by SAWCE in its sole discretion, will occur at the place where SAWCE maintains such records, during SAWCE'S normal business hours and with at least thirty (30) days prior notice. In the event that accounting errors are found, SAWCE reserves the right to address and rectify the alleged errors within fifteen (15) business days. Any audit, objection relating to any accounting statement, or lawsuit arising therefrom, must be made (and lawsuit commenced) no later than one (1) year after the date of the Pay Period in question. Provider hereby waives any longer statute of limitations that may be permitted by law. Provider agrees that in the event Provider brings legal action against SAWCE for a purported breach of the agreement due to a failure to provide an accurate accounting, and a financial review or audit of SAWCE'S books and records yields a finding that the difference between the accounting provided by SAWCE to the Provider and the auditor's findings is five percent (5%) or less, then Provider agrees to reimburse SAWCE for its actual attorneys' fees, costs and disbursements incurred in connection with the Provider's action and/or audit.</p>
<p>7.00. Except as set forth above in Paragraph 3.00 as to notice by e-mail, all notices and/or demands concerning material obligations and claims of breach, provided for or permitted under this Agreement shall be made in writing and either be (i) personally delivered, or (ii) sent by postage prepaid certified mail, return receipt requested, or (iii) delivered by courier service.</p>
<p>Notice to SAWCE shall be as follows: <br />
<br />
Sawce Media Inc.<br />
Attn: Chief Content Officer<br />
410-1275 Hamilton St.<br />
Vancouver, BC V6B 1E2</p>
<p>Notice to Provider shall be as set forth in the &quot;contact information,&quot; and Provider agrees that this information is current and accurate to the best of his/her ability. </p>
<p>8.00. This Agreement shall be deemed executed by the Parties hereto, and all of the terms and conditions set forth herein shall be deeded acknowledged and accepted, upon Provider clicking the &quot;I Agree&quot; button as set forth on this Site.</p>
<p>8.01. This Agreement represents the entire understanding between the Parties and supersedes all previous versions of the Agreement. Any previous Agreement between the Parties is hereby revoked. Notwithstanding the foregoing, this Agreement may be modified from time to time by SAWCE provided that SAWCE provides prior written notice to be delivered to the Content Provider. In the event the Content Provider does not formally object to the modified Content Provider Agreement in writing within ten (10) days of delivery to the Content Provider's registered electronic mail address (provided to SAWCE by Content Provider) (the &quot;Consent Period&quot;), said modified Content Provider Agreement shall be deemed accepted without further notice. In the event Content Provider objects in writing (prior to the expiration of the Consent Period) to the modification or revisions, SAWCE shall have ninety (90) days to remove the Provider Content upon due demand. </p>
<p>9.00. Each individual signing this Agreement (either in paper or electronically), whether signed individually or on behalf of any person and/or entity, warrants and represents that the individual has full authority to so execute this Agreement on behalf of the Party on whose behalf he or she signs. Each of the Parties separately acknowledges and represents that this representation and warranty is accurate and is an essential and material provision of this Agreement and shall survive the execution of this Agreement.</p>
<p>10.00. The rights and obligations set forth above in Paragraphs 2.00, 2.02, 2.04, 2.05, 3.02, 3.04, 3.05, 4.00, 4.01, 4.02, 4.03, 5.00, 5.01, 6.00, 7.00, 8.00 and 8.01 shall survive the termination of this Agreement, as necessary.</p>
<p>11.00. Except for the contact information set forth above in Paragraphs 7.00, 8.00, and 8.01, this Agreement may not be amended or modified in any respect whatsoever except by a writing duly executed by the Parties, and the Parties agree that they shall make no claim(s) at any time that this Agreement has been orally amended or modified.</p>

</td></tr></table>
</div></div>

<?=insert_sawce_footer();?> 

<?php end_focus_content(); ?>
<?/***********************************************************************    
* begin output buffer so we can grab the peripheral content
***********************************************************************/?>
<?php start_peripheral_content(); ?>

<div id="right_page"><div class="padding">
    <div class="right_top">Info</div>
    <div class="header">Learn More</div>
    <div class="section">
        <ul>
            <li class="first"><a href="<?=build_link('about')?>">About Sawce</a></li> 
            <li><a href="<?=build_link('about','spread')?>">How it Works</a></li>
            <li><a href="<?=build_link('about','contact')?>">Contact</a></li>
            <li><a href="<?=build_link('about','terms')?>">Terms and Conditions</a></li>
            <li><a href="<?=build_link('about','privacy')?>">Privacy Policy</a></li>
        </ul>
    </div>
</div></div>

<?php end_peripheral_content(); ?>